### ISSUE TITLE
Change README.MD

### ISSUE THREAD

**Issue by VasilevSaryal** [team-dev-spring-2022/TGBot#1]

**Comment by 0pdd** [comment]
@VasilevSaryal 3 puzzles [#5](https://github.com/team-dev-spring-2022/TGBot/issues/5), [#6](https://github.com/team-dev-spring-2022/TGBot/issues/6), [#7](https://github.com/team-dev-spring-2022/TGBot/issues/7) are still not solved.

**Comment by 0pdd** [comment]
@VasilevSaryal all 3 puzzles are solved here: [#5](https://github.com/team-dev-spring-2022/TGBot/issues/5), [#6](https://github.com/team-dev-spring-2022/TGBot/issues/6), [#7](https://github.com/team-dev-spring-2022/TGBot/issues/7).
