### ISSUE TITLE
Add /help command

### ISSUE THREAD

**Issue by VasilevSaryal** [team-dev-spring-2022/TGBot#2]

**Comment by 0pdd** [comment]
@VasilevSaryal the puzzle [#8](https://github.com/team-dev-spring-2022/TGBot/issues/8) is still not solved.

**Comment by 0pdd** [comment]
@VasilevSaryal the only puzzle [#8](https://github.com/team-dev-spring-2022/TGBot/issues/8) is solved here.

**Comment by 0pdd** [comment]
@VasilevSaryal the puzzle [#8](https://github.com/team-dev-spring-2022/TGBot/issues/8) is still not solved.
