### ISSUE TITLE
main.py:60: сделать команды для завершения цикличного...

### ISSUE THREAD

**Issue by 0pdd** [team-dev-spring-2022/TGBot#28]
The puzzle `3-c7c0a652` from #3 has to be resolved: 

https://github.com/team-dev-spring-2022/TGBot/blob/58489e9628c6f0ee0abf34e66ec2aa9d69f9a52a/main.py#L60-L60

The puzzle was created by fedniko on 09-Feb-22. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by fedniko** [comment]
done
