### ISSUE TITLE
Add Token from BotFather

### ISSUE THREAD

**Issue by VasilevSaryal** [team-dev-spring-2022/TGBot#9]

**Comment by 0pdd** [comment]
@VasilevSaryal the puzzle [#10](https://github.com/team-dev-spring-2022/TGBot/issues/10) is still not solved.

**Comment by 0pdd** [comment]
@VasilevSaryal the only puzzle [#10](https://github.com/team-dev-spring-2022/TGBot/issues/10) is solved here.
